# Generated by Django 6.0 on 2025-12-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('a', 'active'), ('b', 'not active')], max_length=1)),
            ],
        ),
    ]
